### PR TITLE
Username: Fix the undefined when the user name is not set

### LINKED ISSUE #341: User name is show as a undefined
If the user does not have a first name in keycloak, the username will show up as undefined in DAMAP.
Image
Should not show undefined if the user does not have the firstname

### PR DESCRIPTION
**Pull request by andresTabiTuwien**
### Checks

- [ ] Summary updated
- [ ] Version view updated
- [ ] Documentation added
- [ ] Tests added
- [ ] E2e tests created
- [ ] Successfully ran e2e tests before merge

closes GH-

### CODE REVIEW

File: apps/damap-frontend/src/app/components/layout/layout.component.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ export class LayoutComponent implements OnInit, AfterViewInit, OnDestroy {
   }
 
   ngOnInit(): void {
-    this.name = this.auth.getName();
+    this.name = this.auth.getName() ? this.auth.getName() : '';
```
Comment (rekt-hard) [inline apps/damap-frontend/src/app/components/layout/layout.component.ts]: Using the null coalescing operator allows to call the method only once. If the left operand returns a value other than `null` or `undefined`, this value will be assigned - otherwise the right operand will be assigned.
```suggestion
    this.name = this.auth.getName() ?? '';
```

Comment (andresTabiTuwien) [reply apps/damap-frontend/src/app/components/layout/layout.component.ts]: Thanks David, I corrected it.

**Review by rekt-hard — APPROVED** [review]
good catch - thank you
