### PR TITLE
Display dataset size label

### LINKED ISSUE #202: Estimated dataset size range disappears
**Describe the bug**
In Step 3, when adding a dataset, one selects an estimated size from the dropdown list with 10 options that represent a size range, e.g. 100 to 500 GB.  However, once saved, the range changes in the table to the largest range listed.  This largest value also then shows in the template. 

**Is this a regression?**
No.

**To Reproduce**

1. Go to Step 3
2. Add a dataset under new datasets
3. Select an estimated size that is a range, e.g. 1-5 GB
4. See size in table change to <5 GB instead of 1-5 GB

**Expected behavior**
The size in table should change to 1-5 GB instead of <5 GB.  The change should also cascade to all the 3 templates. 

**Screenshots**

Image

Image

Image

### PR DESCRIPTION
**Pull request by lpandath**
## Description

Dataset sizes are displayed, shifting from technical size notations to labels that reflect typical data size ranges (e.g., "1 - 5 GB"). 

#### What does this PR do?

image

### Checks

- [ ] Summary updated
- [ ] Version view updated
- [ ] Documentation added
- [ ] Tests added
- [ ] E2e tests created
- [ ] Successfully ran e2e tests before merge

closes GH-

### CODE REVIEW

**Comment by lpandath** [comment]
@rekt-hard the PR from backend too: https://github.com/tuwien-csd/damap-backend/pull/208

Thank you! :)

File: libs/damap/src/lib/components/dmp/specify-data/dataset-table/dataset-table.component.ts [hunk 1]
```diff
@@ -1,16 +1,19 @@
 import { Component, EventEmitter, Input, Output } from '@angular/core';
+import { FILE_SIZES, FILE_TYPES } from '../data-specs';
```
Comment (rekt-hard) [inline libs/damap/src/lib/components/dmp/specify-data/dataset-table/dataset-table.component.ts]: FILE_TYPES is not used

File: libs/damap/src/lib/components/dmp/specify-data/dataset-table/dataset-table.component.ts [hunk 2]
```diff
@@ -25,9 +28,15 @@ export class DatasetTableComponent {
   }>();
 
   readonly datasetSource: any = DataSource;
+  sizeOptions = FILE_SIZES;
```
Comment (rekt-hard) [inline libs/damap/src/lib/components/dmp/specify-data/dataset-table/dataset-table.component.ts]: no need for extra variable since we already have `FILE_SIZES` as variable

File: libs/damap/src/lib/components/dmp/specify-data/dataset-table/dataset-table.component.ts [hunk 3]
```diff
@@ -25,9 +28,15 @@ export class DatasetTableComponent {
...
 
   constructor(public dialog: MatDialog) {}
 
+  getSizeLabel(size: number): string {
+    const foundSize = this.sizeOptions.find(option => size <= option.size);
```
Comment (rekt-hard) [inline libs/damap/src/lib/components/dmp/specify-data/dataset-table/dataset-table.component.ts]: `FILE_SIZES'` can be used here

**Review by rekt-hard — COMMENTED** [review]
Working well.
Just a small issue for the `I don't know yet` option.
image

**Comment by lpandath** [comment]
@rekt-hard no issues from my side:
image

**Comment by rekt-hard** [comment]
@lpandath in the front end

**Comment by lpandath** [comment]
> @lpandath in the front end

updated now the PR. Thank you!

**Review by rekt-hard — APPROVED** [review]
good job!
