### PR TITLE
global: Use default behaviour for changedetector

### LINKED ISSUE #333: Table does not automatically update
**Describe the bug**
When uploading a file to be analyzed, the UI does not get updated automatically. An interaction with another UI element is necessary to trigger the re rendering.

The issue is present in the commit for v4.2.0 all the way to commit [f3772752c269ba76193e3d8e99a86c9f5649cc5a](https://github.com/tuwien-csd/damap-frontend/commit/f3772752c269ba76193e3d8e99a86c9f5649cc5a). So the assumption is that it was introduced in this commit.

With this commit, also the highlighting of the selected tab was removed.

**Is this a regression?**
Yes

**To Reproduce**

1. Create a DMP
2. Go to section 3
3. Click on `Specify dataset` for new data
4. Click on `Upload sample data`
5. Select a file for upload
6. Observe that the progress bar does not update and the result will not be added to the table.

**Expected behavior**
Progress bar gets updated.
Result of uploaded file is added to the table.

**Screenshots**
***Before***
- Screenshot from 2024-10-09 18-45-44
- Screenshot from 2024-10-09 18-46-21
- Screenshot from 2024-10-09 18-46-32

***Now***
- Screenshot from 2024-10-09 18-47-40
- After interacting with the file upload again
- image

**Environment**

- Browser: firefox
- Damap version: v4.2.0 to commit f3772752c269ba76193e3d8e99a86c9f5649cc5a

**Additional context**

### PR DESCRIPTION
**Pull request by rekt-hard**
#### What does this PR do?
Use default change detection for components.
For tables, no change was detected when updating data in the background. It would have required a manual push to render again.

### Checks

- [ ] Summary updated
- [ ] Version view updated
- [ ] Documentation added
- [ ] Tests added
- [ ] E2e tests created
- [ ] Successfully ran e2e tests before merge

closes #333

### CODE REVIEW

File: apps/damap-frontend/src/app/components/layout/layout.component.ts [hunk 1]
```diff
@@ -37,8 +35,7 @@ export class LayoutComponent implements OnInit, AfterViewInit, OnDestroy {
   public isCollapsed: boolean = false;
   public templateDataLayout = layoutTemplate;
   public icon = 'info';
-  public infoString: BehaviorSubject<any> | null;
```
Comment (rekt-hard) [inline apps/damap-frontend/src/app/components/layout/layout.component.ts:40]: Removed as it was not used (only initialized)

File: apps/damap-frontend/src/app/components/layout/layout.component.ts [hunk 2]
```diff
@@ -64,8 +61,9 @@ export class LayoutComponent implements OnInit, AfterViewInit, OnDestroy {
     this.observer.observe([Breakpoints.Handset]).subscribe(result => {
       this.isSmallScreen = result.matches;
       this.checkScreenSize();
-      this.handleRouteChange();
```
Comment (rekt-hard) [inline apps/damap-frontend/src/app/components/layout/layout.component.ts:67]: This should only be relevant when the route changes, which we are already subscribed to

**Review by andresTabiTuwien — APPROVED** [review]
Thank you, the refactor for the handleRouteChange function and the removal of the onPush strategy fixes the problem.
