### PR TITLE
Licensing: Add no/custom license & selector for restricted datasets

### LINKED ISSUE #448: Licensing: restricted datasets should have a license selector displayed
**Describe the bug**
Like with an open dataset, there should be a license selector here.

Image

Additionally, there is no option to not select a license - this should also be changed. 

**Is this a regression?**
No.

**Expected behavior**
Licenese selector should be in the restricted section and it should be possible to select no license.

**Screenshots**

**Environment**

- Damap version 4.5.0

### PR DESCRIPTION
**Pull request by BlueTechie**
## Description

Bugfix
#### What does this PR do?

Display license selector for datasets with restricted access as well (before: only open access)
Added the options "no license" and "custom license":
grafik

#### Dependencies
Backend changes necessary: https://github.com/tuwien-csd/damap-backend/pull/373

closes GH-448

### CODE REVIEW

File: libs/damap/src/lib/widgets/license-wizard/license-wizard-list.ts [hunk 1]
```diff
@@ -578,6 +577,30 @@ export const pddl = {
...
+  name: 'license.wizard.license.custom.name',
+  priority: null,
+  available: null,
+  url: null,
+  description: 'license.wizard.license.custom.description',
+  categories: [],
+  labels: null,
+  code: null,
+  compatibility: null,
+};
```
Comment (ghost) [inline libs/damap/src/lib/widgets/license-wizard/license-wizard-list.ts:603]: As mentioned in tuwien-csd/damap-backend#373, I would suggest using the proper SPDX identifiers:

```suggestion
export const nolicense = {
  id: 'LicenseRef-AllRightsReserved',
  name: 'license.wizard.license.nolicense.name',
  priority: null,
  available: null,
  url: null,
  description: 'license.wizard.license.nolicense.description',
  categories: [],
  labels: null,
  code: null,
  compatibility: null,
};
export const custom = {
  id: 'LicenseRef-Proprietary',
  name: 'license.wizard.license.custom.name',
  priority: null,
  available: null,
  url: null,
  description: 'license.wizard.license.custom.description',
  categories: [],
  labels: null,
  code: null,
  compatibility: null,
};
```

**Comment by BlueTechie** [comment]
Unfortunately due to the way our architecture is built, the ids of the constants in the _libs/damap/src/lib/widgets/license-wizard/license-wizard-list.ts_ file have to match a valid enum value in the backend (ELicense.java) so we will leave it as is for the time being.

**Comment by ghost** [comment]
> Unfortunately due to the way our architecture is built, the ids of the constants in the _libs/damap/src/lib/widgets/license-wizard/license-wizard-list.ts_ file have to match a valid enum value in the backend (ELicense.java) so we will leave it as is for the time being.

Yes, makes sense - we have issue #453 to remember tackling the architectural change. This PR works for me, maybe @ValentinFutterer can review it to make sure I haven't missed anything regarding the internals.

**Review by ghost — APPROVED** [review]

**Review by ValentinFutterer — APPROVED** [review]
Good work!
